version: "3"
services:
  nginx:
    container_name: nginx-server
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./client/build:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app
  app:
    container_name: node-backend
    restart: always
    build: .
    # ports:
    #   - "5000:5000"